name: Deploy
on: push

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1
    - name: helm directory
      run: cd helm/opendistro-es/
    - name: ubuntu
      run: snap install google-cloud-sdk --classic && gcloud init
    - name: 'Deploy'
      uses: 'deliverybot/helm@master'
      with:
        token: '${{ github.token }}'
        chart: '.'
        release: 'opendistro'
        namespace: 'default'
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG_FILE }}'
