name: Deploy
on: push

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Setup Minikube
      uses: manusa/actions-setup-minikube@v2.0.0
      with:
        minikube version: 'v1.9.2'
        kubernetes version: 'v1.18.2'
#        github token: ${{ secrets.GITHUB_TOKEN }}
    - name: wait for kubectl
      run: sleep 60
    - name: Interact with the cluster
      run: kubectl get all --all-namespaces
    - name: helm
      run: helm version
#    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
#      with:
#        version: '290.0.1'
#        project_id: ${{ secrets.GCP_PROJECT_ID }}
#        service_account_key: ${{ secrets.GCP_SA_KEY }}
#        export_default_credentials: true
    - name: helm directory
      run: ls helm/opendistro-es/ ~/.kubeconfig
    - name: deploy postgres to cluster
      uses: wahyd4/kubectl-helm-action@master
      with:
        args: |
          helm upgrade --install opendistro helm/opendistro-es -n es      
#    - uses: hahow/install-helm-chart-action@v1.0.1
#      with:
#        gcloud_auth_key: ${{ secrets.GCP_SA_KEY }}
#        gcloud_project_id: ${{ secrets.GCP_PROJECT_ID }}
#        cluster_name: ${{ secrets.GCP_CLUSTER_NAME }}
#        cluster_region: us-central1-c
#        release_namespace: default
#        release_name: opendistro
#        chart_name: helm/opendistro-es/
