name: Deploy
on: push

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - name: helm directory
      run: cd helm/opendistro-es/
    - uses: ./setup-gcloud # Set up ADC to make authenticated request to service
      with:
        service_account_email: ${{ secrets.DEPLOY_CLOUDRUN_SA_EMAIL }}
        service_account_key: ${{ secrets.DEPLOY_CLOUDRUN_SA_KEY_B64 }}
        export_default_credentials: true
    - name: 'Deploy'
      uses: 'deliverybot/helm@master'
      with:
        token: '${{ github.token }}'
        chart: '.'
        release: 'opendistro'
        namespace: 'default'
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG_FILE }}'
