name: Deploy
on: push

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Setup gcloud environment
      uses: GoogleCloudPlatform/github-actions@0.1.2
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: helm directory
      run: cd helm/opendistro-es/ && which gcloud
    - name: 'Deploy'
      uses: 'deliverybot/helm@master'
      with:
        token: '${{ github.token }}'
        chart: '.'
        release: 'opendistro'
        namespace: 'default'
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG_FILE }}'
